# Generated by Django 5.1.4 on 2024-12-09 13:04

from django.db import migrations, models

 
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('appid', models.CharField(max_length=100)),
                ('state', models.IntegerField()),
                ('amount', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
